<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
    <parent><groupId>dk.sdu.cbse</groupId><artifactId>gamelab-parent</artifactId><version>1.0.0</version></parent>
    <artifactId>core</artifactId>
    <dependencies>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>common</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>player</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>enemy</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>asteroids</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>weapon</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>dk.sdu.cbse</groupId><artifactId>collision</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.openjfx</groupId><artifactId>javafx-controls</artifactId><version>${javafx.version}</version></dependency>
    </dependencies>
    <build><plugins><plugin><groupId>org.openjfx</groupId><artifactId>javafx-maven-plugin</artifactId><version>0.0.8</version><configuration><mainClass>dk.sdu.cbse.core.GameLabApp</mainClass></configuration></plugin></plugins></build>
</project>
